services:
  verificationrotation:
    image: ghcr.io/compactly8274/verificationrotation:latest
    container_name: verificationrotation
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /mnt/user/appdata:/mnt/user/appdata
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
      - ./.env:/app/.env:rw
